movielist/urls.py
from django.conf.urls import include,url

from . import views

urlpatterns = [
    url(r'^(?P<movie_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^$', views.intro, name='intro'),
    url(r'^search/$', views.search, name='search'),
    url(r'^wishlist/$', views.wishlist, name='wishlist'),
    url(r'^login/$', views.login, name='login'),
    url(r'^profile_page/$', views.profile_page, name='profile_page'),
	url(r'^score_list/$', views.score_list, name='score_list'),
	url(r'^add_to_wishlist/(?P<movie_id>[0-9]+)/$', views.add_to_wishlist, name="add_to_wishlist"),
	url(r'^remove_from_wishlist/(?P<movie_id>[0-9]+)/$', views.remove_from_wishlist, name="remove_from_wishlist"),
	url(r'^score_submission/(?P<movie_id>[0-9]+)/$', views.score_submission, name="score_submission"),
	url(r'^score_update/(?P<movie_id>[0-9]+)/$', views.score_update, name="score_update"),
	url(r'^test/$', views.test, name='test')
]

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from movielist import views

urlpatterns = [
	url(r'^$', views.home),
	url(r'^movielist/', include('movielist.urls', namespace="movielist")),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
]

movielist/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from decimal import *

# Create your models here.

class Movie(models.Model):
	title_year = models.CharField(max_length=100)
	title = models.CharField(max_length=100)
	year = models.IntegerField()
	# description = models.TextField(max_length=5000, blank=True, default="") #don't need both
	# language = models.CharField(max_length=50)
	# picture_link = FileField()
	genre = models.CharField(max_length=200)
	# stars = models.CharField(max_length=100)
	length_min = models.IntegerField()
	rating_overall = models.DecimalField(max_digits=2, decimal_places=1)
	# actor = models.ManyToManyField(Actor, blank=True) 	
	votes = models.IntegerField(default=0)
	# wishlist_users = model.ManyToManyField(User, through='Wishlist') #wishees? ratees?
	raters = models.ManyToManyField(User, through='Score')
	def __str__(self):
		return self.title_year

# can we change this to a manytomany relationship? The difference with the Toseelist is that you have to add the rating to each relationship
class Rating(models.Model):
	movies = models.ForeignKey(Movie) 
	pub_date = models.DateTimeField('date published')
	user = models.ForeignKey(User) 
	rating = models.DecimalField(max_digits=3, decimal_places=1, null=True) #rating-->value

	def __str__(self):
		return self.user.username

# can we change this to a manytomany relationship? The difference with the Toseelist is that you have to add the rating to each relationship
class Score(models.Model):
	movies = models.ForeignKey(Movie) 
	pub_date = models.DateTimeField('date published')
	user = models.ForeignKey(User) 
	score = models.DecimalField(max_digits=3, decimal_places=1, null=True)	 #rating-->value

	def __str__(self):
		return self.user.username


# class Actor(models.Model):
# 	name = models.CharField(max_length=30)
# 	movies = models.ManyToManyField(Movie) 
# 	user_name = models.CharField(max_length=100)
# 	pub_date = models.DateTimeField('date published')

# 	def __str__(self):
# 		return self.name

class Toseelist(models.Model):
	movies = models.ManyToManyField(Movie) 
	pub_date = models.DateTimeField('date published')
	user = models.OneToOneField(User)
	# on_delete 

	def __str__(self):
		return self.user.username

movielist/forms.py
from django.forms import ModelForm, Form
from movielist.models import Score, Toseelist

class ScoreForm(ModelForm):
	class Meta:
		model = Score
		fields = ['score']
		widgets = {}

class ToseelistForm(Form):
	class Meta:
		model = Toseelist
		widgets = {}

# class ActorForm(ModelForm):
# 	class Meta:
# 		model = Actor
# 		fields = ['name']
# 		widgets = {}

movielist/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from movielist.models import Movie, Score, Toseelist
from movielist.forms import ScoreForm, ToseelistForm
from django.core.urlresolvers import reverse	
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib import messages
import datetime


def home(request):
	full_list = Movie.objects.all()
	return render(request, 'movielist/intro.html', {"full_list": full_list})

def intro(request):
	full_list = Movie.objects.all()
	return render(request, 'movielist/intro.html', {"full_list": full_list})

def detail(request, movie_id):
	movie = get_object_or_404(Movie, pk=movie_id)
	form_s = ScoreForm(request.POST or None)
	form_t = ToseelistForm(request.POST or None)
	user = request.user
	if user.score_set.get(movies=movie):
		score = user.score_set.get(movies=movie)
	else:
		score = ("")
	return render(request, 'movielist/detail.html', {'score':score, 'movie': movie, 'form_s': form_s, 'form_t': form_t} )
	# return render(request, 'movielist/detail.html', {'movie': movie, 'form_s': form_s, 'form_t': form_t} )
	# return HttpResponseRedirect(reverse('movielist:detail'), args=(movie, form_s, form_t))

def score_submission(request, movie_id):
	movie = get_object_or_404(Movie, pk=movie_id)
	form_s = ScoreForm(request.POST or None) 
	form_t = ToseelistForm(request.POST or None) #do we need this?
	user = request.user
	if form_s.is_valid():
		score = Score()
		score.movies = movie
		score.score = form_s.cleaned_data['score'] 
		score.user = user
		score.pub_date = datetime.datetime.now()
		score.save()
# 		# return HttpResponseRedirect(reverse('movielist:detail'), args=(movie,)) Don't get this to work
	return redirect('movielist:detail', movie_id= movie.id)

def score_update(request, movie_id):
	movie = get_object_or_404(Movie, pk=movie_id)
	form_s = ScoreForm(request.POST or None) 
	form_t = ToseelistForm(request.POST or None) #do we need this?
	user = request.user
	score = user.score_set.get(movies=movie)
	if form_s.is_valid():
		score.delete()
		score = Score()
		score.movies = movie
		score.score = form_s.cleaned_data['score'] 
		score.user = user
		score.pub_date = datetime.datetime.now()
		score.save()
# 		# return HttpResponseRedirect(reverse('movielist:detail'), args=(movie,)) Don't get this to work
	return redirect('movielist:detail', movie_id= movie.id)

def add_to_wishlist(request, movie_id):
	movie = get_object_or_404(Movie, pk=movie_id)
	form_s = ScoreForm(request.POST or None) #do we need this?
	form_t = ToseelistForm(request.POST or None)
	user = request.user
	if form_t.is_valid():
		if user.toseelist:
			toseelist = user.toseelist
		else:
			toseelist = user.toseelist.create()
		toseelist.pub_date = datetime.datetime.now()
		toseelist.save()
		toseelist.movies.add(movie)
	# return HttpResponseRedirect(reverse('movielist:detail'), args=(movie, form_s, form_t))
	# return render(request, 'movielist/detail.html', {'movie': movie, 'form_s': form_s, 'form_t': form_t} )
	return redirect('movielist:detail', movie_id= movie.id)

def remove_from_wishlist(request, movie_id):
	movie = get_object_or_404(Movie, pk=movie_id)
	form_s = ScoreForm(request.POST or None)
	form_t = ToseelistForm(request.POST or None)
	user = request.user
	toseelist = user.toseelist
	if form_t.is_valid():
		toseelist.movies.remove(movie)
	return redirect('movielist:detail', movie_id= movie.id)


def search(request):
	search = request.GET.get("search_terms")
	if search:
		search_list = Movie.objects.filter(title__icontains=search)
		return render(request, 'movielist/search.html', {"search_list": search_list})
	return render(request, 'movielist/search.html')

@login_required
def wishlist(request):
	toseelist = request.user.toseelist
	movies = toseelist.movies.all
	return render(request, 'movielist/wishlist.html', {"movies": movies})

@login_required
def score_list(request):
	if request.user.is_authenticated(): # This is not necessary if you also have login_required. Change after deciding setup of page
		score_list = Score.objects.filter(user=request.user)
	else: 
		score_list = Score.objects.all()
	return render(request, 'movielist/score_list.html', {"score_list": score_list})


@login_required
# do you want to make profile page public? otherwise maybe dashboard
def profile_page(request):
	user = request.user
	return render(request, 'movielist/profile_page.html')

def login(request, error=None):
	username = request.POST["username"]
	password = request.POST['password']
	user = authenticate(username=username, password=password)
	if user is not None:
		login(request, user)
		# Probably need to do: if user-authenticated, don't login again
		# if user.is_active:
		# 	login(request, user)
		return render(request, 'movielist/profile_page.html')
	else: 
		error = "Something went wrong, please try again"
		return render(request, 'registration/login.html')

def test(request):
	return render(request, "movielist/test.html")

movielist/templates/movielist/actor.html
{% extends 'layout/layout.html' %}

{% block title %}Movielist{% endblock %}

{% block content %}




<h1>You're at the introduction page to the movielist. Soon, you can keep track of which movies you've already seen and score them</h1>

<ul>
{% for actor in actor_list %}
	<li>{{ actor.name }} </li>
		{% for movie in movie_set.actor_list %}
		<li>{{ movie.title }} </li>
		{% endfor %}
{% endfor %}
</ul> 

{% endblock %}

movielist/templates/movielist/detail.html
{% extends 'layout/layout.html' %}

{% block title %}Movie Detail{% endblock %}

{% block content %}

<h1>You're at the detail page of {{ movie.title_year }} </h1>

<h3> Movie name: {{ movie.title }} </h3>
<h3> Released in: {{ movie.year }} </h3>
<!-- <h3> Description: {{ movie.description }} </h3> -->
<!-- <h3> Language: {{ movie.language }} </h3> -->
<h3> Genre: {{ movie.genre }} </h3>
<!-- <h3> Stars: {{ movie.stars }} </h3> -->
<h3> Length (min.): {{ movie.length_min }} </h3>
<h3> Overall rating: {{ movie.rating_overall }} </h3>


{% if user.is_authenticated %} 

<h3><strong> Rate this movie: </strong></h3>

{% if user in movie.raters.all %}

<h3> You already rated this movielist.You rated it {{ score.score }} out of 10</h3>

<form action="{% url 'movielist:score_update' movie.id %}" method="post">
	{% csrf_token %}
	{{ form_s.as_p }}
	<input type="submit" value="Update" />
</form>

{% else %}

<form action="{% url 'movielist:score_submission' movie.id %}" method="post">
	{% csrf_token %}
	{{ form_s.as_p }}
	<input type="submit" value="Add" />
</form>

{% endif %}

{% if movie in user.toseelist.movies.all %}

<h3><strong> Delete this movie from your wishlist: </strong></h3>
<form action="{% url 'movielist:remove_from_wishlist' movie.id %}" method="post">
	{% csrf_token %}
	{{ form_t.as_p }}
	<input type="submit" value="Delete" />
</form>

{% else %}

<h3><strong> Add this movie to your wishlist: </strong></h3>
<form action="{% url 'movielist:add_to_wishlist' movie.id %}" method="post">
	{% csrf_token %}
	{{ form_t.as_p }}
	<input type="submit" value="Add" />
</form>

{% endif %}



<!-- {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
 -->
{% endif %}


{% endblock %}

movielist/templates/movielist/intro.html
{% extends 'layout/layout.html' %}

{% block title %}Movielist{% endblock %}

{% block content %}




<h1>You're at the introduction page to the movielist. Soon, you can keep track of which movies you've already seen and score them</h1>

<ul>
{% for movie in full_list %}
	<li><a href="/movielist/{{ movie.id }}/"> {{ movie.title_year }}</a>, overall score: {{ movie.rating_overall }} </li>
{% endfor %}
</ul> 

{% endblock %}

movielist/templates/movielist/profile_page.html
{% extends 'layout/layout.html' %}

{% block title %}Profile{% endblock %}

{% block content %}

<h3> This is the profile page of {{ user.username }} </h3>

{% endblock %}

movielist/templates/movielist/score_list.html
{% extends 'layout/layout.html' %}

{% block title %}Wishlist{% endblock %}

{% block content %}

<h1>Hi! This is your personal ratings overview </h1>


<ul>
{% for score in score_list %}
	<li><a href="/movielist/{{ score.movies.id }}/"> {{ score.movies.title }}</a>, rated {{ score.score }} </li>
{% endfor %}
</ul> 

{% endblock %}

movielist/templates/movielist/search.html
{% extends 'layout/layout.html' %}

{% block title %}Movielist{% endblock %}

{% block content %}

<form method='GET' action="">
    <input type="text" name="search_terms" placeholder="Enter your search terms"/>
    <input type="submit" value="Go"/ class="btn btn-default">
</form>

<ul>
{% for movie in search_list %}
	<li><a href="/movielist/{{ movie.id }}/"> {{ movie.title_year }}, </a> overall score: {{ movie.rating_overall }} </li>
{% endfor %}
</ul> 

{% endblock %}

movielist/templates/movielist/seenlist.html
{% extends 'layout/layout.html' %}

{% block title %}Wishlist{% endblock %}

{% block content %}

<h1>Hi! This is your personal seenlist </h1>

{% for movie in movies %}
	{{ movie.title }} {{ seenlist.user.username }}
{% endfor %}

{% endblock %}

movielist/templates/movielist/test.html
<?php

$likeMovie = "Yes"; 
$bt1 = "Movie"; 

if ($likeMovie == "Yes"){
  $valueMovie = "Unlike";
} else {
  $valueMovie = "Like";  
}

$person="Daan";

?>

<html>

  <head>
    <script type="text/javascript">
      function toggleLike(myVal, btId){
        var person ="<?php echo $person; ?>";
        if (myVal=="Like"){
          document.getElementById(btId).value = "Unlike";
        } else {
          document.getElementById(btId).value = "Like";
        }
        alert (person+" "+myVal+" "+btn1);
       // now doesn't seem to work 
             
      }
          
    </script>
  
  </head>

  <body>
    <h1>Hello!</h1>
  
Do you like this movie?
<input onClick="toggleLike(this.value, this.id)" type="button" value="<?php echo $valueMovie; ?>" id="<?php echo $bt1; ?>">

</body>
</html>

movielist/templates/movielist/wishlist.html
{% extends 'layout/layout.html' %}

{% block title %}Wishlist{% endblock %}

{% block content %}

<h1>Hi! This is your personal wishlist </h1>

<ul>
{% for movie in movies %}
	<li><a href="/movielist/{{ movie.id }}/"> {{ movie.title_year }} </a></li>
{% endfor %}
</ul> 

{% endblock %}